Move Documentation CI (#105)
* doc test

* test

* update

* add

* add

* addsui

* docupdate

* update

* udpate

* test

* test

* test

* update

* modified

* cleanup

* finalcleanup

* docupdates

* last_test

* final

diff --git a/.github/workflows/move_test.yml b/.github/workflows/move_test.yml
--- a/.github/workflows/move_test.yml
+++ b/.github/workflows/move_test.yml
@@ -5,11 +5,11 @@ on:
       paths:
         - '.github/workflows/**'
         - 'packages/**'
-  push: 
+  push:
     branches:
       - main
 
-concurrency: 
+concurrency:
     group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
     cancel-in-progress: true
 
@@ -40,3 +40,20 @@ jobs:
             (cd "$dir" && sui move test)
           fi
         done
+
+    - name: Run documentation script
+      run: |
+        bash ./scripts/docgen.sh
+      shell: bash
+
+    - name: Check for changes in move-docs directories
+      run: |
+        output=$(git status --porcelain | grep ' packages/.*/move-docs/' || true)
+        echo "Filtered git status output: $output"
+        if [[ -n "$output" ]]; then
+          echo "Changes in move-docs directories are not committed. Please commit these changes by running scripts/docgen.sh before merging."
+          exit 1  # Fail the job to indicate that documentation is not up-to-date
+        else
+          echo "No changes in move-docs directories. Documentation is up-to-date."
+        fi
+      shell: bash
