fix conflict

diff --git a/.github/workflows/move_test.yml b/.github/workflows/move_test.yml
--- a/.github/workflows/move_test.yml
+++ b/.github/workflows/move_test.yml
@@ -2,16 +2,16 @@ name: Move Test CI
 
 on:
   pull_request:
-      paths:
-        - '.github/workflows/move_test.yml'
-        - 'packages/**'
+    paths:
+      - '.github/workflows/move_test.yml'
+      - 'packages/**'
   push:
     branches:
       - main
 
 concurrency:
-    group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
-    cancel-in-progress: true
+  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
+  cancel-in-progress: true
 
 jobs:
   test:
@@ -41,19 +41,19 @@ jobs:
             fi
           done
 
-    - name: Run documentation script
-      run: |
-        bash ./scripts/docgen.sh
-      shell: bash
+      - name: Run documentation script
+        run: |
+          bash ./scripts/docgen.sh
+        shell: bash
 
-    - name: Check for changes in move-docs directories
-      run: |
-        output=$(git status --porcelain | grep ' packages/.*/move-docs/' || true)
-        echo "Filtered git status output: $output"
-        if [[ -n "$output" ]]; then
-          echo "Changes in move-docs directories are not committed. Please commit these changes by running scripts/docgen.sh before merging."
-          exit 1  # Fail the job to indicate that documentation is not up-to-date
-        else
-          echo "No changes in move-docs directories. Documentation is up-to-date."
-        fi
-      shell: bash
+      - name: Check for changes in move-docs directories
+        run: |
+          output=$(git status --porcelain | grep ' packages/.*/move-docs/' || true)
+          echo "Filtered git status output: $output"
+          if [[ -n "$output" ]]; then
+            echo "Changes in move-docs directories are not committed. Please commit these changes by running scripts/docgen.sh before merging."
+            exit 1  # Fail the job to indicate that documentation is not up-to-date
+          else
+            echo "No changes in move-docs directories. Documentation is up-to-date."
+          fi
+        shell: bash
